defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 1
  working_directory: ~/ember-metrics-pendo

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - ember-metrics-pendo-node10-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: yarn install --non-interactive --pure-lockfile
      - save_cache:
          key: ember-metrics-pendo-node10-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/ember-metrics-pendo/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint Handlebars
          command: yarn lint:hbs
      - run:
          name: Lint JavaScript
          command: yarn lint:js

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn ember try:one ember-default --skip-cleanup=true

  test_lts_3_12:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember LTS 3.12
          command: yarn ember try:one ember-lts-3.12 --skip-cleanup=true

  test_lts_3_16:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember LTS 3.16
          command: yarn ember try:one ember-lts-3.16 --skip-cleanup=true

  test_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Release
          command: yarn ember try:one ember-release --skip-cleanup=true

  test_beta:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Beta
          command: yarn ember try:one ember-beta --skip-cleanup=true

  test_canary:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Canary
          command: yarn ember try:one ember-canary --skip-cleanup=true

  test_default_with_jquery:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests Ember Default With jQuery
          command: yarn ember try:one ember-default-with-jquery --skip-cleanup=true

workflows:
  version: 2
  test_matrix:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - test_lts_3_12:
          requires:
            - install_dependencies
      - test_lts_3_16:
          requires:
            - install_dependencies
      - test_release:
          requires:
            - install_dependencies
      - test_beta:
          requires:
            - install_dependencies
      - test_canary:
          requires:
            - install_dependencies
      - test_default_with_jquery:
          requires:
            - install_dependencies
